version: '3.4'

services:
  previsaotempo.app:
    ports:
      - 3000:80

  previsaotempo.api:
    ports:
      - 5000:80

    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
                
  previsaotempo.db:
    ports:
      - "5432:5432"