version: '3.4'

services:
  previsaotempo.app:
    ports:
      - 3000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
  previsaotempo.api:
    ports:
      - 5000:80

    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
                
  database:
    ports:
      - "5432:5432"