version: '3.4'
services:
  previsaotempo.app:
    image: ${DOCKER_REGISTRY-}searchweatherapp
    container_name: previsaotempo-app
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    depends_on:
        - previsaotempo.api
  previsaotempo.api:
    container_name: previsaotempo.api
    image: ${DOCKER_REGISTRY-}searchweather
    build:
      context: .
      dockerfile: api/PrevisaoTempo.WebApi/Dockerfile
    depends_on:
        - previsaotempo.db
  previsaotempo.db:
    container_name: previsaotempo.db
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql